### ISSUE TITLE
resim format convert

### ISSUE THREAD

**Issue by koma-xrd** [atlantis-l/Radix-Desktop-Tool#1]
i love this tool - it would be really useful for having a resim format converter, not only mainnet and stokenet. Would this be easy to implement?

**Comment by atlantis-l** [comment]
Done. It can be downloaded now.

**Comment by tychiadet** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
aetherplex, @giu7, @antonyuhnovets, @ee-ehab-xx, @graper-guo, @amlcodes, @cryptothink629, @jpmsegurado, @0xAmey, @whoami2323, @kalbhairavaa, @lraunakl, @dmandalinic, @ishengchiu, @jinnzy, @rayeaster, @arkaydeus, @zanaca, @TimoTong, @alikonuk1, @developerjake, @tmol0003, @mani3h, @SOSO-eng, @wazzan, @shawnhcd, @ghayat2, @sbtobb, @Nightlights524, @KiselevMaxim, @qiaoba-cat, @yclsl, @Ming900907, @qinshang007, @lusiwei, @rdfsx, @merklefruit, @CalvinOne, @willyrgf, @pavelkostyurin, @TkCoder666, @hanaduy, @Duxina, @krazedegen, @blkrt, @x4rMa, @foright, @tomjrtsmith, @redisun, @jondoescoding

**Comment by iamcameronwatson** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
hsyndeniz, @taoyq1988, @atav32, @khoa-nvk, @rafalos, @dev-gavinfang, @jaanauati, @Stipa9, @ratipr, @Pharbi, @codeVerine, @anhskohbo, @dlxg, @johnknutsson, @ulissesferreira, @taufikrahman29, @prahaladbelavadi, @HenryFanDi, @freehere107, @bludnic, @NeerajGodiyal, @johnedma, @flynn-eye, @willlittle, @underwater, @XUGAOBO, @nhat416, @racg0092, @AnasGhareib, @quocthinhvo, @lukorito, @KABBOUCHI, @ouhenio, @jeremiahm1smith, @linhongzhou, @tyceone, @baydakovss, @pcw109550, @bionicles, @timelessover, @chavee, @mikefaust, @ramsunvtech, @amosaustin, @lthomiso, @Spatika, @rusalexch, @shammellee, @kzawadi, @tspringk

**Comment by iamcameronwatson** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
mi2valley, @lijameshao, @kevinji, @This-Is-Prince, @xavieresp1, @sentinelweb, @dartharthur, @downzer0, @w3-api, @gp888, @toniowhola, @0xblockboy, @startprojekt, @antaintan, @datis7756, @siteriaitaliana, @missrhyme, @lidabing, @yoowinsu, @dawsonsewell, @jasonnoahchoi, @ilarioni, @m00s, @System-Glitch, @Holden-Lin, @jabez128, @MollyXuemn, @liupishui, @cdschneider, @wax13003, @FacadeCloud, @codigocarvalho, @takuan-osho, @hexiaokang, @quardz, @aturX, @AngeloSchulerPiletti, @MatthieuScarset, @joe20182, @DavidODonovan, @ktyoku, @Gabberuthkx, @chenyinz, @edison0951, @DELIGHT100, @learn2grid, @IDouble, @mikhail-khalizev, @luandevpro, @mingchan88
